/**
 * Terminal domain types for the aterm application.
 *
 * This module centralizes all shared TypeScript types used across the
 * frontend for tabs, themes, and PTY dimensions. Keeping them in a single
 * file avoids circular imports between components (Tabbar, TerminalView,
 * App) and ensures the config schema and Rust backend stay in sync.
 */

/**
 * ThemeName — the set of supported color themes.
 * - "aterm-dark": default dark theme (Tabby-inspired, #141416 background)
 * - "aterm-light": light variant for bright environments
 * - "nord": Nord palette for low-contrast preference
 * The enum is validated on the frontend via Zod (ConfigSchema) and
 * serialized as a string to the Rust backend (Config.theme).
 */
export type ThemeName = "aterm-dark" | "aterm-light" | "nord";

/**
 * Tab — minimal metadata for a single terminal session / tab.
 * - id: UUID v4 generated by the Rust backend (pty::create_session) and used
 *   as the key for all IPC calls (write_to_session, resize_session, close_session,
 *   get_cwd) and for xterm event channels (pty:data:{id}, pty:exit:{id}).
 * - title: display title shown in the tab bar. Initially "tab N" then updated
 *   via xterm onTitleChange (shell OSC title, e.g., "user@host: /path") or
 *   via App.handleTitleChange callback. No cwd stored here — cwd is queried
 *   on-demand via `invoke("get_cwd")` to keep the type lean and avoid staleness
 *   when the shell does `cd` without notifying the frontend.
 */
export interface Tab {
  id: string;
  title: string;
}

/**
 * ThemeColors — full ANSI palette plus UI colors for xterm.js.
 * Mirrors the ITheme interface from @xterm/xterm but typed explicitly so
 * App.tsx can define static palettes per ThemeName and pass them to
 * TerminalView for `new Terminal({ theme })` and live updates via
 * `term.options.theme = themeColors`.
 *
 * Fields:
 * - background/foreground/cursor/cursorAccent/selectionBackground: core UI
 * - black/red/green/yellow/blue/magenta/cyan/white + bright variants: ANSI 16
 */
export interface ThemeColors {
  background: string;
  foreground: string;
  cursor: string;
  cursorAccent: string;
  selectionBackground: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}


